// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type LoginToken struct {
	Token     uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpireAt  time.Time
}

type User struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Name          string
	EmailAddr     string
	EmailVerified bool
}
